#nullable enable
using GLControl = OpenTK.GLControl.GLControl;
using Ruri.RipperHook.GUI.Components;
namespace Ruri.RipperHook.GUI;

partial class MainForm
{
	private System.ComponentModel.IContainer? components = null;
	private MenuStrip menuStrip1 = null!;
	private ToolStripMenuItem fileToolStripMenuItem = null!;
	private ToolStripMenuItem loadFileToolStripMenuItem = null!;
	private ToolStripMenuItem loadFolderToolStripMenuItem = null!;
	private ToolStripMenuItem appendFileToolStripMenuItem = null!;
	private ToolStripMenuItem appendFolderToolStripMenuItem = null!;
	private ToolStripSeparator fileToolStripSeparator1 = null!;
	private ToolStripMenuItem resetToolStripMenuItem = null!;
	private ToolStripMenuItem directExportToolStripMenuItem = null!;
	private ToolStripMenuItem directExportFromFileToolStripMenuItem = null!;
	private ToolStripMenuItem directExportFromFolderToolStripMenuItem = null!;
	private ToolStripMenuItem exportToolStripMenuItem = null!;
	private ToolStripMenuItem exportAllAssetsMenuItem = null!;
	private ToolStripMenuItem exportAllConvertedAssetsMenuItem = null!;
	private ToolStripMenuItem exportAllJsonAssetsMenuItem = null!;
	private ToolStripMenuItem exportAllYamlAssetsMenuItem = null!;
	private ToolStripMenuItem exportAllRawAssetsMenuItem = null!;
	private ToolStripMenuItem exportSelectedAssetsMenuItem = null!;
	private ToolStripMenuItem exportSelectedConvertedAssetsMenuItem = null!;
	private ToolStripMenuItem exportSelectedJsonAssetsMenuItem = null!;
	private ToolStripMenuItem exportSelectedYamlAssetsMenuItem = null!;
	private ToolStripMenuItem exportSelectedRawAssetsMenuItem = null!;
	private ToolStripMenuItem exportFilteredAssetsMenuItem = null!;
	private ToolStripMenuItem exportFilteredConvertedAssetsMenuItem = null!;
	private ToolStripMenuItem exportFilteredJsonAssetsMenuItem = null!;
	private ToolStripMenuItem exportFilteredYamlAssetsMenuItem = null!;
	private ToolStripMenuItem exportFilteredRawAssetsMenuItem = null!;
	private ContextMenuStrip assetListContextMenuStrip = null!;
	private ToolStripMenuItem contextExportSelectedAssetsMenuItem = null!;
	private ToolStripMenuItem contextExportSelectedConvertedAssetsMenuItem = null!;
	private ToolStripMenuItem contextExportSelectedJsonAssetsMenuItem = null!;
	private ToolStripMenuItem contextExportSelectedYamlAssetsMenuItem = null!;
	private ToolStripMenuItem contextExportSelectedRawAssetsMenuItem = null!;
	private SplitContainer splitContainer1 = null!;
	private TabControl tabControl1 = null!;
	private TabPage tabPage1 = null!;
	private TabPage tabPage2 = null!;
	private TabPage tabPage3 = null!;
	private GOHierarchy sceneTreeView = null!;
	private TextBox treeSearch = null!;
	private TreeView hookTreeView = null!;
	private Panel hookActionPanel = null!;
	private Label hookSummaryLabel = null!;
	private Button reloadHooksButton = null!;
	private ListView assetListView = null!;
	private ColumnHeader columnHeaderName = null!;
	private ColumnHeader columnHeaderContainer = null!;
	private ColumnHeader columnHeaderType = null!;
	private ColumnHeader columnHeaderPathID = null!;
	private ColumnHeader columnHeaderSize = null!;
	private TextBox listSearch = null!;
	private ComboBox typeFilterComboBox = null!;
	private TabControl tabControl2 = null!;
	private TabPage tabPage4 = null!;
	private TabPage tabPage5 = null!;
	private TabPage tabPage6 = null!;
	private Panel previewPanel = null!;
	private Label assetInfoLabel = null!;
	private PictureBox imagePreviewBox = null!;
	private GLControl glControl = null!;
	private TextBox textPreviewBox = null!;
	private TextBox yamlTextBox = null!;
	private TextBox hexTextBox = null!;
	private Panel audioPanel = null!;
	private Label audioStatusLabel = null!;
	private StatusStrip statusStrip1 = null!;
	private ToolStripStatusLabel toolStripStatusLabel1 = null!;

	protected override void Dispose(bool disposing)
	{
		if (disposing)
		{
			components?.Dispose();
		}
		base.Dispose(disposing);
	}

	private void InitializeComponent()
	{
		components = new System.ComponentModel.Container();
		menuStrip1 = new MenuStrip();
		fileToolStripMenuItem = new ToolStripMenuItem();
		loadFileToolStripMenuItem = new ToolStripMenuItem();
		loadFolderToolStripMenuItem = new ToolStripMenuItem();
		appendFileToolStripMenuItem = new ToolStripMenuItem();
		appendFolderToolStripMenuItem = new ToolStripMenuItem();
		fileToolStripSeparator1 = new ToolStripSeparator();
		resetToolStripMenuItem = new ToolStripMenuItem();
		directExportToolStripMenuItem = new ToolStripMenuItem();
		directExportFromFileToolStripMenuItem = new ToolStripMenuItem();
		directExportFromFolderToolStripMenuItem = new ToolStripMenuItem();
		exportToolStripMenuItem = new ToolStripMenuItem();
		exportAllAssetsMenuItem = new ToolStripMenuItem();
		exportAllConvertedAssetsMenuItem = new ToolStripMenuItem();
		exportAllJsonAssetsMenuItem = new ToolStripMenuItem();
		exportAllYamlAssetsMenuItem = new ToolStripMenuItem();
		exportAllRawAssetsMenuItem = new ToolStripMenuItem();
		exportSelectedAssetsMenuItem = new ToolStripMenuItem();
		exportSelectedConvertedAssetsMenuItem = new ToolStripMenuItem();
		exportSelectedJsonAssetsMenuItem = new ToolStripMenuItem();
		exportSelectedYamlAssetsMenuItem = new ToolStripMenuItem();
		exportSelectedRawAssetsMenuItem = new ToolStripMenuItem();
		exportFilteredAssetsMenuItem = new ToolStripMenuItem();
		exportFilteredConvertedAssetsMenuItem = new ToolStripMenuItem();
		exportFilteredJsonAssetsMenuItem = new ToolStripMenuItem();
		exportFilteredYamlAssetsMenuItem = new ToolStripMenuItem();
		exportFilteredRawAssetsMenuItem = new ToolStripMenuItem();
		assetListContextMenuStrip = new ContextMenuStrip(components);
		contextExportSelectedAssetsMenuItem = new ToolStripMenuItem();
		contextExportSelectedConvertedAssetsMenuItem = new ToolStripMenuItem();
		contextExportSelectedJsonAssetsMenuItem = new ToolStripMenuItem();
		contextExportSelectedYamlAssetsMenuItem = new ToolStripMenuItem();
		contextExportSelectedRawAssetsMenuItem = new ToolStripMenuItem();
		splitContainer1 = new SplitContainer();
		tabControl1 = new TabControl();
		tabPage1 = new TabPage();
		tabPage2 = new TabPage();
		tabPage3 = new TabPage();
		sceneTreeView = new GOHierarchy();
		treeSearch = new TextBox();
		hookTreeView = new TreeView();
		hookActionPanel = new Panel();
		hookSummaryLabel = new Label();
		reloadHooksButton = new Button();
		assetListView = new ListView();
		columnHeaderName = new ColumnHeader();
		columnHeaderContainer = new ColumnHeader();
		columnHeaderType = new ColumnHeader();
		columnHeaderPathID = new ColumnHeader();
		columnHeaderSize = new ColumnHeader();
		listSearch = new TextBox();
		typeFilterComboBox = new ComboBox();
		tabControl2 = new TabControl();
		tabPage4 = new TabPage();
		tabPage5 = new TabPage();
		tabPage6 = new TabPage();
		previewPanel = new Panel();
		imagePreviewBox = new PictureBox();
		glControl = new GLControl();
		textPreviewBox = new TextBox();
		yamlTextBox = new TextBox();
		hexTextBox = new TextBox();
		audioPanel = new Panel();
		audioStatusLabel = new Label();
		assetInfoLabel = new Label();
		statusStrip1 = new StatusStrip();
		toolStripStatusLabel1 = new ToolStripStatusLabel();
		menuStrip1.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)splitContainer1).BeginInit();
		splitContainer1.Panel1.SuspendLayout();
		splitContainer1.Panel2.SuspendLayout();
		splitContainer1.SuspendLayout();
		tabControl1.SuspendLayout();
		tabPage2.SuspendLayout();
		tabControl2.SuspendLayout();
		tabPage4.SuspendLayout();
		previewPanel.SuspendLayout();
		((System.ComponentModel.ISupportInitialize)imagePreviewBox).BeginInit();
		audioPanel.SuspendLayout();
		statusStrip1.SuspendLayout();
		SuspendLayout();
		menuStrip1.Items.AddRange([fileToolStripMenuItem, directExportToolStripMenuItem, exportToolStripMenuItem]);
		menuStrip1.Location = new System.Drawing.Point(0, 0);
		menuStrip1.Name = "menuStrip1";
		menuStrip1.Size = new System.Drawing.Size(1264, 24);
		fileToolStripMenuItem.DropDownItems.AddRange([loadFileToolStripMenuItem, loadFolderToolStripMenuItem, appendFileToolStripMenuItem, appendFolderToolStripMenuItem, fileToolStripSeparator1, resetToolStripMenuItem]);
		fileToolStripMenuItem.Text = "File";
		loadFileToolStripMenuItem.Text = "Load files";
		loadFileToolStripMenuItem.Click += loadFile_Click;
		loadFolderToolStripMenuItem.Text = "Load folder";
		loadFolderToolStripMenuItem.Click += loadFolderToolStripMenuItem_Click;
		appendFileToolStripMenuItem.Text = "Append files";
		appendFileToolStripMenuItem.Click += appendFileToolStripMenuItem_Click;
		appendFolderToolStripMenuItem.Text = "Append folder";
		appendFolderToolStripMenuItem.Click += appendFolderToolStripMenuItem_Click;
		resetToolStripMenuItem.Text = "Reset";
		resetToolStripMenuItem.Click += resetToolStripMenuItem_Click;
		// Top-level button: load an input + export directly, no asset list / scene tree.
		// Equivalent to the headless AR_ExportDirectly hook, but UI-triggered. Splits into
		// file-vs-folder so single-bundle spot tests share the same path-derivation logic
		// as whole-game exports.
		directExportToolStripMenuItem.Text = "Direct Export";
		directExportToolStripMenuItem.DropDownItems.AddRange([directExportFromFileToolStripMenuItem, directExportFromFolderToolStripMenuItem]);
		directExportFromFileToolStripMenuItem.Text = "From file(s)...";
		directExportFromFileToolStripMenuItem.Click += directExportFromFileToolStripMenuItem_Click;
		directExportFromFolderToolStripMenuItem.Text = "From folder...";
		directExportFromFolderToolStripMenuItem.Click += directExportFromFolderToolStripMenuItem_Click;
		exportToolStripMenuItem.DropDownItems.AddRange([exportAllAssetsMenuItem, exportSelectedAssetsMenuItem, exportFilteredAssetsMenuItem]);
		exportToolStripMenuItem.Text = "Export";
		exportAllAssetsMenuItem.DropDownItems.AddRange([exportAllConvertedAssetsMenuItem, exportAllJsonAssetsMenuItem, exportAllYamlAssetsMenuItem, exportAllRawAssetsMenuItem]);
		exportAllAssetsMenuItem.Text = "All assets";
		exportAllConvertedAssetsMenuItem.Text = "Converted";
		exportAllConvertedAssetsMenuItem.Click += exportAllAssetsMenuItem_Click;
		exportAllJsonAssetsMenuItem.Text = "JSON";
		exportAllJsonAssetsMenuItem.Click += exportAllJsonAssetsMenuItem_Click;
		exportAllYamlAssetsMenuItem.Text = "YAML";
		exportAllYamlAssetsMenuItem.Click += exportAllYamlAssetsMenuItem_Click;
		exportAllRawAssetsMenuItem.Text = "Raw";
		exportAllRawAssetsMenuItem.Click += exportAllRawAssetsMenuItem_Click;
		exportSelectedAssetsMenuItem.DropDownItems.AddRange([exportSelectedConvertedAssetsMenuItem, exportSelectedJsonAssetsMenuItem, exportSelectedYamlAssetsMenuItem, exportSelectedRawAssetsMenuItem]);
		exportSelectedAssetsMenuItem.Text = "Selected assets";
		exportSelectedConvertedAssetsMenuItem.Text = "Converted";
		exportAllAssetsMenuItem.Click += exportAllAssetsMenuItem_Click;
		exportSelectedConvertedAssetsMenuItem.Click += exportSelectedAssetsMenuItem_Click;
		exportSelectedJsonAssetsMenuItem.Text = "JSON";
		exportSelectedJsonAssetsMenuItem.Click += exportSelectedJsonAssetsMenuItem_Click;
		exportSelectedYamlAssetsMenuItem.Text = "YAML";
		exportSelectedYamlAssetsMenuItem.Click += exportSelectedYamlAssetsMenuItem_Click;
		exportSelectedRawAssetsMenuItem.Text = "Raw";
		exportSelectedRawAssetsMenuItem.Click += exportSelectedRawAssetsMenuItem_Click;
		exportFilteredAssetsMenuItem.DropDownItems.AddRange([exportFilteredConvertedAssetsMenuItem, exportFilteredJsonAssetsMenuItem, exportFilteredYamlAssetsMenuItem, exportFilteredRawAssetsMenuItem]);
		exportFilteredAssetsMenuItem.Text = "Filtered assets";
		exportFilteredConvertedAssetsMenuItem.Text = "Converted";
		exportSelectedAssetsMenuItem.Click += exportSelectedAssetsMenuItem_Click;
		exportFilteredConvertedAssetsMenuItem.Click += exportFilteredAssetsMenuItem_Click;
		exportFilteredJsonAssetsMenuItem.Text = "JSON";
		exportFilteredJsonAssetsMenuItem.Click += exportFilteredJsonAssetsMenuItem_Click;
		exportFilteredYamlAssetsMenuItem.Text = "YAML";
		exportFilteredYamlAssetsMenuItem.Click += exportFilteredYamlAssetsMenuItem_Click;
		exportFilteredRawAssetsMenuItem.Text = "Raw";
		exportFilteredRawAssetsMenuItem.Click += exportFilteredRawAssetsMenuItem_Click;
		exportFilteredAssetsMenuItem.Click += exportFilteredAssetsMenuItem_Click;
		assetListContextMenuStrip.Items.AddRange([contextExportSelectedAssetsMenuItem]);
		contextExportSelectedAssetsMenuItem.DropDownItems.AddRange([contextExportSelectedConvertedAssetsMenuItem, contextExportSelectedJsonAssetsMenuItem, contextExportSelectedYamlAssetsMenuItem, contextExportSelectedRawAssetsMenuItem]);
		contextExportSelectedAssetsMenuItem.Text = "Export selected";
		contextExportSelectedConvertedAssetsMenuItem.Text = "Converted";
		contextExportSelectedConvertedAssetsMenuItem.Click += exportSelectedAssetsMenuItem_Click;
		contextExportSelectedJsonAssetsMenuItem.Text = "JSON";
		contextExportSelectedJsonAssetsMenuItem.Click += exportSelectedJsonAssetsMenuItem_Click;
		contextExportSelectedYamlAssetsMenuItem.Text = "YAML";
		contextExportSelectedYamlAssetsMenuItem.Click += exportSelectedYamlAssetsMenuItem_Click;
		contextExportSelectedRawAssetsMenuItem.Text = "Raw";
		contextExportSelectedRawAssetsMenuItem.Click += exportSelectedRawAssetsMenuItem_Click;
		splitContainer1.Dock = DockStyle.Fill;
		splitContainer1.Location = new System.Drawing.Point(0, 24);
		splitContainer1.Name = "splitContainer1";
		splitContainer1.Panel1.Controls.Add(tabControl1);
		splitContainer1.Panel2.Controls.Add(tabControl2);
		splitContainer1.Size = new System.Drawing.Size(1264, 657);
		splitContainer1.SplitterDistance = 760;
		tabControl1.Controls.Add(tabPage1);
		tabControl1.Controls.Add(tabPage2);
		tabControl1.Controls.Add(tabPage3);
		tabControl1.Dock = DockStyle.Fill;
		tabPage1.Controls.Add(sceneTreeView);
		tabPage1.Controls.Add(treeSearch);
		tabPage1.Location = new System.Drawing.Point(4, 24);
		tabPage1.Text = "Scene Hierarchy";
		tabPage1.UseVisualStyleBackColor = true;
		tabPage2.Controls.Add(assetListView);
		tabPage2.Controls.Add(typeFilterComboBox);
		tabPage2.Controls.Add(listSearch);
		tabPage2.Location = new System.Drawing.Point(4, 24);
		tabPage2.Text = "Asset List";
		tabPage2.UseVisualStyleBackColor = true;
		tabPage3.Controls.Add(hookTreeView);
		tabPage3.Controls.Add(hookActionPanel);
		tabPage3.Controls.Add(hookSummaryLabel);
		tabPage3.Location = new System.Drawing.Point(4, 24);
		tabPage3.Text = "Hooks";
		tabPage3.UseVisualStyleBackColor = true;
		sceneTreeView.CheckBoxes = true;
		sceneTreeView.Dock = DockStyle.Fill;
		sceneTreeView.HideSelection = false;
		sceneTreeView.Location = new System.Drawing.Point(0, 23);
		sceneTreeView.Name = "sceneTreeView";
		sceneTreeView.NodeMouseClick += sceneTreeView_NodeMouseClick;
		treeSearch.Dock = DockStyle.Top;
		treeSearch.PlaceholderText = "Search hierarchy";
		treeSearch.TextChanged += treeSearch_TextChanged;
		hookSummaryLabel.Dock = DockStyle.Top;
		hookSummaryLabel.Height = 48;
		hookSummaryLabel.Text = "No hooks enabled.";
		hookSummaryLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
		hookActionPanel.Dock = DockStyle.Bottom;
		hookActionPanel.Height = 44;
		hookActionPanel.Controls.Add(reloadHooksButton);
		reloadHooksButton.Text = "Reload Files";
		reloadHooksButton.AutoSize = true;
		reloadHooksButton.Location = new System.Drawing.Point(8, 10);
		reloadHooksButton.Click += reloadHooksButton_Click;
		hookTreeView.CheckBoxes = true;
		hookTreeView.Dock = DockStyle.Fill;
		hookTreeView.HideSelection = false;
		hookTreeView.AfterCheck += hookTreeView_AfterCheck;
		assetListView.Columns.AddRange([columnHeaderName, columnHeaderContainer, columnHeaderType, columnHeaderPathID, columnHeaderSize]);
		assetListView.Dock = DockStyle.Fill;
		assetListView.FullRowSelect = true;
		assetListView.HideSelection = false;
		assetListView.Location = new System.Drawing.Point(0, 48);
		assetListView.MultiSelect = true;
		assetListView.Name = "assetListView";
		assetListView.Size = new System.Drawing.Size(752, 581);
		assetListView.TabIndex = 0;
		assetListView.UseCompatibleStateImageBehavior = false;
		assetListView.View = View.Details;
		assetListView.ContextMenuStrip = assetListContextMenuStrip;
		assetListView.SelectedIndexChanged += assetListView_SelectedIndexChanged;
		assetListView.MouseUp += assetListView_MouseUp;
		columnHeaderName.Text = "Name";
		columnHeaderName.Width = 220;
		columnHeaderContainer.Text = "Container";
		columnHeaderContainer.Width = 220;
		columnHeaderType.Text = "Type";
		columnHeaderType.Width = 120;
		columnHeaderPathID.Text = "PathID";
		columnHeaderPathID.Width = 90;
		columnHeaderSize.Text = "Size";
		columnHeaderSize.Width = 90;
		listSearch.Dock = DockStyle.Top;
		listSearch.PlaceholderText = "Search";
		listSearch.TextChanged += listSearch_TextChanged;
		typeFilterComboBox.Dock = DockStyle.Top;
		typeFilterComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
		typeFilterComboBox.SelectedIndexChanged += typeFilterComboBox_SelectedIndexChanged;
		tabControl2.Controls.Add(tabPage4);
		tabControl2.Controls.Add(tabPage5);
		tabControl2.Controls.Add(tabPage6);
		tabControl2.Dock = DockStyle.Fill;
		tabPage4.Controls.Add(previewPanel);
		tabPage4.Location = new System.Drawing.Point(4, 24);
		tabPage4.Text = "Preview";
		tabPage4.UseVisualStyleBackColor = true;
		tabPage5.Controls.Add(yamlTextBox);
		tabPage5.Location = new System.Drawing.Point(4, 24);
		tabPage5.Text = "YAML";
		tabPage5.UseVisualStyleBackColor = true;
		tabPage6.Controls.Add(hexTextBox);
		tabPage6.Location = new System.Drawing.Point(4, 24);
		tabPage6.Text = "Hex";
		tabPage6.UseVisualStyleBackColor = true;
		previewPanel.Controls.Add(imagePreviewBox);
		previewPanel.Controls.Add(glControl);
		previewPanel.Controls.Add(textPreviewBox);
		previewPanel.Controls.Add(audioPanel);
		previewPanel.Controls.Add(assetInfoLabel);
		previewPanel.Dock = DockStyle.Fill;
		imagePreviewBox.Dock = DockStyle.Fill;
		imagePreviewBox.SizeMode = PictureBoxSizeMode.Zoom;
		glControl.API = OpenTK.Windowing.Common.ContextAPI.OpenGL;
		glControl.APIVersion = new Version(3, 3, 0, 0);
		glControl.BackColor = System.Drawing.SystemColors.ControlDarkDark;
		glControl.Dock = DockStyle.Fill;
		glControl.Flags = OpenTK.Windowing.Common.ContextFlags.Default;
		glControl.IsEventDriven = true;
		glControl.Profile = OpenTK.Windowing.Common.ContextProfile.Core;
		glControl.Visible = false;
		glControl.Load += glControl_Load;
		glControl.Paint += glControl_Paint;
		glControl.Resize += glControl_Resize;
		glControl.MouseDown += glControl_MouseDown;
		glControl.MouseMove += glControl_MouseMove;
		glControl.MouseUp += glControl_MouseUp;
		glControl.MouseWheel += glControl_MouseWheel;
		textPreviewBox.Dock = DockStyle.Fill;
		textPreviewBox.Multiline = true;
		textPreviewBox.ReadOnly = true;
		textPreviewBox.ScrollBars = ScrollBars.Both;
		textPreviewBox.WordWrap = false;
		textPreviewBox.HideSelection = false;
		yamlTextBox.Dock = DockStyle.Fill;
		yamlTextBox.Multiline = true;
		yamlTextBox.ReadOnly = true;
		yamlTextBox.ScrollBars = ScrollBars.Both;
		yamlTextBox.WordWrap = false;
		yamlTextBox.HideSelection = false;
		hexTextBox.Dock = DockStyle.Fill;
		hexTextBox.Multiline = true;
		hexTextBox.ReadOnly = true;
		hexTextBox.ScrollBars = ScrollBars.Both;
		hexTextBox.WordWrap = false;
		hexTextBox.HideSelection = false;
		tabControl2.SelectedIndexChanged += tabControl2_SelectedIndexChanged;
		audioPanel.Controls.Add(audioStatusLabel);
		audioPanel.Dock = DockStyle.Fill;
		audioStatusLabel.Dock = DockStyle.Top;
		audioStatusLabel.Text = "Audio preview available via export";
		assetInfoLabel.Dock = DockStyle.Top;
		assetInfoLabel.Height = 120;
		assetInfoLabel.Text = "No asset loaded.";
		statusStrip1.Items.AddRange([toolStripStatusLabel1]);
		statusStrip1.Location = new System.Drawing.Point(0, 681);
		toolStripStatusLabel1.Text = "Ready";
		AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
		AutoScaleMode = AutoScaleMode.Font;
		ClientSize = new System.Drawing.Size(1264, 703);
		Controls.Add(splitContainer1);
		Controls.Add(statusStrip1);
		Controls.Add(menuStrip1);
		MainMenuStrip = menuStrip1;
		Name = "MainForm";
		StartPosition = FormStartPosition.CenterScreen;
		Text = "RuriAssetRipper";
		menuStrip1.ResumeLayout(false);
		menuStrip1.PerformLayout();
		splitContainer1.Panel1.ResumeLayout(false);
		splitContainer1.Panel2.ResumeLayout(false);
		((System.ComponentModel.ISupportInitialize)splitContainer1).EndInit();
		splitContainer1.ResumeLayout(false);
		tabControl1.ResumeLayout(false);
		tabPage1.ResumeLayout(false);
		tabPage1.PerformLayout();
		tabPage2.ResumeLayout(false);
		tabPage2.PerformLayout();
		tabPage3.ResumeLayout(false);
		tabControl2.ResumeLayout(false);
		tabPage4.ResumeLayout(false);
		tabPage5.ResumeLayout(false);
		tabPage6.ResumeLayout(false);
		previewPanel.ResumeLayout(false);
		previewPanel.PerformLayout();
		((System.ComponentModel.ISupportInitialize)imagePreviewBox).EndInit();
		audioPanel.ResumeLayout(false);
		statusStrip1.ResumeLayout(false);
		statusStrip1.PerformLayout();
		ResumeLayout(false);
		PerformLayout();
	}
}
